### ISSUE TITLE
Feature Request: Comment upon resolution with an explanation

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [LivInTheLookingGlass/ManifoldMarketManager#5]
Each rule should define an explanation text for itself. An example would be to use a tree in the form of a bulleted list.

Example:

```
- Multiple Values (<output>)
  - Resolves to a dictionary of answers to weights
  - Value 1
    - Specific Value (<value>)
    - Weight: 1
  - Value 2
    - Random Index (<index>)
    - Method
      - Name: <method>
      - Params: <args>
        - Keyword: value
    - Seed: <seed>
    - Rounds: <rounds>
    - Weight: 1 
```

**Comment by gappleto97** [comment]
Okay, explanations are now working, but I'm gated by the fact that there is no support for commenting via the API (https://github.com/manifoldmarkets/manifold/issues/821). I'll probably wait on specific case explanations until that's settled

**Comment by gappleto97** [comment]
Okay, infrastructure for this on my end is ready
